### ISSUE TITLE
Stuck At Approving, ReferenceError: balance is not defined

### ISSUE THREAD

**Issue by BartuCulha** [thesphere/karmic-dapp#35]
Steps to reproduce:
Connect Wallet
Click Approve all tokens
Click approve button

dapp gets stuck at approving. I am not able to see metamask popup.

here's console log:

Approving all the tokens
index-66b0979a375b8fc5e59e.js:1 Uncaught (in promise) ReferenceError: balance is not defined
    at index-66b0979a375b8fc5e59e.js:1:36314
    at Array.filter (<anonymous>)
    at index-66b0979a375b8fc5e59e.js:1:36226
    at l (main-12d082cd9c513dcd9e16.js:1:57542)
    at Generator._invoke (main-12d082cd9c513dcd9e16.js:1:57330)
    at Generator.next (main-12d082cd9c513dcd9e16.js:1:57967)
    at n (_app-7f78b454f6675a9f2963.js:1:675542)
    at s (_app-7f78b454f6675a9f2963.js:1:675745)
    at _app-7f78b454f6675a9f2963.js:1:675804
    at new Promise (<anonymous>)

![The-Sphere (5)](https://user-images.githubusercontent.com/24368665/156049604-80e09445-560d-43fe-8e50-f79b7d8187cf.png)

**Comment by BartuCulha** [comment]
it's fixed 👍
